### ISSUE TITLE
Multiple Commands Cause Right Panel to Collapse

### ISSUE THREAD

**Issue by garylyp** [AY1920S1-CS2103T-T09-2/main#83]
Component:
-Ui

Description:
-When Help command or Edit command are called successfully, the newly created right Ui panel from #13 collapses to the center. Seems like the middle column is removed from the screen when these commands are called.

Steps:
1a) Run "edit 1 n/New Name" or 
1b) Run "help"

Expected: 
1a) Field gets edited correctly
1b) Help pop-up appears
2) Right panel remains at its position. All three panels remain in view.

Actual: 
1a) Field gets edited correctly
1b) Help pop-up appears
2) Right panel collapses to the left. Centre panel disappears from view.

**Comment by weihaw08** [comment]
The right panel is meant to be a place holder for the Schedule List. 

The most likely reason why the right panel collapses after you perform a function is because I have temporarily made use of the same FilteredList object to display the function results and the original list at the right panel.

Will make the changes to the UI at a later stage.

**Comment by t-cheepeng** [comment]
> The most likely reason why the right panel collapses after you perform a function is because I have temporarily made use of the same FilteredList object to display the function results and the original list at the right panel. Furthermore, the FilteredList object will always be displayed after a function call (as of now).

Noted. Once ExerHealth has been morphed, we can get started on this issue here. The person who is doing scheduling(@t-cheepeng) will probably fix this bug since the UI is related.
